- COMPRENSIÓN DE COLECCIONES

1 - Comprensión de listas

1.1 Ejemplo 1

In [ ]:
# Usando funciones y ciclos
def cuadrado(n):
    return n**2
lista = []
for i in range(10):
    lista.append(cuadrado(i))
print(lista)

In [ ]:
# Usando programación funcional
lista = list(map(lambda x: x ** 2, range(10)))
print(lista)

In [ ]:
# Usando comprensión de listas
lista = [x ** 2 for x in range(10)]
print(lista)

1.2 Ejemplo 2

In [ ]:
# Usando funciones y ciclos
def es_par(n):
    return n%2 == 0
lista = []
for i in range(10):
    if es_par(i) == True:
        lista.append(i)
print(lista)

In [ ]:
# Usando programación funcional
lista = list(filter(lambda x: x % 2 == 0, range(10)))
print(lista)

In [ ]:
# Usando comprensión de listas
lista = [x for x in range(10) if x % 2 == 0]
print(lista)

1.3 Ejemplo 3

In [ ]:
# Usando funciones y ciclos
def es_par(n):
    return n%2 == 0

def cuadrado(n):
    return n**2

lista = []
for i in range(10):
    if es_par(i) == True:
        lista.append(cuadrado(i))
print(lista)

In [ ]:
# Usando programación funcional
lista = list(map(lambda x:x**2, filter(lambda x: x % 2 == 0, range(10))))
print(lista)

In [ ]:
# Usando comprensión de listas
lista = [x ** 2 for x in range(10) if x % 2 == 0]
print(lista)

1.4 Ejemplo 4

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando funciones y ciclos
def mayor_5(notas):
    lista = []
    for (nombre, nota) in notas.items():
        if nota >= 5:
             lista.append(nombre)
    return lista

print(mayor_5(notas))

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando programación funcional
lista = list(map(lambda notas:notas[0], filter(lambda notas: notas[1] >= 5, list(notas.items()))))
print(lista)

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando comprensión de listas
lista = [nombre for (nombre, nota) in notas.items() if nota >= 5]
print(lista)

2 - Comprensión de diccionarios

2.1 Ejemplo 1

In [ ]:
palabras = ['I', 'love', 'Python']

# Usando funciones y ciclos
def palabras_tamaño(palabras):
    diccionario={} 
    for palabra in palabras:
             diccionario[palabra] = len(palabra)
    return diccionario
print(palabras_tamaño(palabras))

In [ ]:
palabras = ['I', 'love', 'Python']
# Usando programación funcional
diccionario = dict(zip(palabras,[len(palabra) for palabra in palabras]))
print(diccionario)

In [ ]:
palabras = ['I', 'love', 'Python']
# Usando comprensión de diccionarios
diccionario = {palabra:len(palabra) for palabra in palabras}
print(diccionario)

2.2 Ejemplo 2

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando funciones y ciclos
def notas_mayor_5(notas):
    diccionario={} 
    for nombre,nota in notas.items():
        if nota>=5:
            diccionario[nombre] = nota + 1
    return diccionario
print(notas_mayor_5(notas))

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando programación funcional
notas_mayor_5=dict(filter(lambda x: x[1] >=5, notas.items()))
diccionario = dict(map(lambda x: (x[0],x[1]+1), notas_mayor_5.items()))                  
print(diccionario)

In [ ]:
notas = {'Carmen':5, 'Antonio':4, 'Juan':8, 'Mónica':9, 'María': 6, 'Pablo':3}
# Usando comprensión de diccionarios
diccionario={nombre: nota +1 for (nombre, nota) in notas.items() if nota >= 5}
print(diccionario)

3 - Comprensión de conjuntos

In [ ]:
# Usando funciones y ciclos
def divisible_entre_3(rangos):
    conjunto=set()
    for numero in rangos:
        if numero%3==0:
            conjunto.add(numero)
    return conjunto
print(divisible_entre_3(range(0, 20)))

In [ ]:
# Usando programación funcional
conjunto=set(filter(lambda numero: numero % 3 == 0,range(0, 20)))                 
print(conjunto)

In [ ]:
# Usando comprensión de conjuntos
conjunto = {numero for numero in range(0, 20) if numero % 3 == 0}
print(conjunto)

- EXCEPCIONES

1.1 Control de errores mediante excepciones

In [ ]:
print(1 / 0)  # Error al intentar dividir por 0.

1.2 Como manejar ZeroDivisionError en Python 

Considera la siguiente función, dividir(), toma 2 argumentos num y div y retorna el resultado o cociente de dividir num/ div.

In [ ]:
def dividir(num,div):
    return num/div

Llamar a la función con diferentes números retorna el resultado de la división.

In [ ]:
res = dividir(100,8)
print(res)
res = dividir(568,64)
print(res)

El código anterior funciona hasta que tratamos de dividir entre cero:

In [ ]:
dividir(27,0)

Podemos tratar esta división entre cero como una excepción, haciendo lo siguiente:

In [34]:
def dividir(num,div):
    return num/div
try:
    num = float(input("Ingrese dividendo: "))
    div = float(input("Ingrese divisor: "))
    res = dividir(num, div)
    print(res)
except Exception:
    print("Trataste de dividir entre cero :( ")

Ingrese dividendo: 27
Ingrese divisor: 0
Trataste de dividir entre cero :( 


1.3 Como enfrentar TypeError en  Python

Pensemos en una función llamada mas_10(), que toma un número como argumento, le añade 10, y retorna el resultado de la suma.

In [35]:
def mas_10(num):
  return num + 10

 Podemos llamar a la función mas_10() con cualquier número y funcionará correctamente, como podemos ver en el siguiente ejemplo:

In [36]:
resultado = mas_10(89)
print(resultado)

99


Ahora llamemos a mas_10() con "cinco" en lugar de 5.

In [37]:
mas_10("cinco")

TypeError: can only concatenate str (not "int") to str

Ahora, ejecutando el código de bajo,  ya que estamos especificando que TypeError es una excepción el programa no se detendrá y te notificara que el argumento es inválido.

In [38]:
mi_num = "cinco"
try:
  resultado = mas_10(mi_num)
  print(resultado)
except TypeError:
  print("El argumento `mi_num` deberia ser un número")

El argumento `mi_num` deberia ser un número


1.4 Como manejar IndexError en Python

Miremos la siguiente lista

In [39]:
mi_lista = ["Python","C","C++","JavaScript"]

En este ejemplo, mi_lista tiene 4 elementos. Los índices válidos son 0, 1, 2, 3  y -1, -2, -3, -4 si usas indexación negativa.

In [40]:
print(mi_lista[2])

C++


Si tratas de acceder a la lista con un índice fuera del rango permitido, ocurrirá un error en la ejecución y aparecerá el error IndexError

In [41]:
print(mi_lista[4])

IndexError: list index out of range

En el siguiente código, intentamos acceder a un elemento con la variable buscar_ind

In [42]:
mi_lista = ["Python","C","C++","JavaScript"]
buscar_ind = 3
try:
  print(mi_lista[buscar_ind])
except IndexError:
  print("Lo siento, el indice esta fuera de rango")

JavaScript


Aquí podemos ver nuestro mensaje personalizado para la excepción

In [43]:
mi_lista = ["Python","C","C++","JavaScript"]
buscar_ind = 4
try:
  print(mi_lista[buscar_ind])
except IndexError:
  print("Lo siento, el indice esta fuera de rango")

Lo siento, el indice esta fuera de rango


1.5 Como manejar KeyError en Python

In [44]:
mi_dict ={"clave1":"valor1", "clave2":"valor2", "clave3":"valor3"}
buscar_clave = "clave no existente"
print(mi_dict[buscar_clave])

KeyError: 'clave no existente'

In [45]:
try:
  print(mi_dict[buscar_clave])
except KeyError:
  print("¡Lo siento, clave invalida!")

¡Lo siento, clave invalida!


También es posible añadir información extra; como el nombre de la clave inválida.

In [46]:
try:
  print(mi_dict[buscar_clave])
except KeyError as variable:
  print(f"¡Lo siento, {variable} no es una clave valida!")

¡Lo siento, 'clave no existente' no es una clave valida!


- LA LIBRERÍA DATETIME

1- Los tipos de datos $\color{red}{\text{date}}$, $\color{red}{\text{time}}$ y $\color{red}{\text{datetime}}$

In [47]:
from datetime import date, time, datetime
date(2020, 12, 25)

datetime.date(2020, 12, 25)

In [48]:
time(13,30,5)

datetime.time(13, 30, 5)

In [49]:
datetime(2020, 12, 25, 13, 30, 5)

datetime.datetime(2020, 12, 25, 13, 30, 5)

In [50]:
print(datetime(2020, 12, 25, 13, 30, 5))

2020-12-25 13:30:05


2- Acceso a los componentes de una fecha

In [51]:
from datetime import date, time, datetime
print(date.today())
dt = datetime.now()
print(dt)
print(dt.year)
print(dt.month)
print(dt.day)
print(dt.hour)
print(dt.minute)
print(dt.second)
print(dt.microsecond)

2023-06-06
2023-06-06 21:03:54.690864
2023
6
6
21
3
54
690864


3 - Conversión de fechas en cadenas con diferentes formatos

In [57]:
from datetime import date, time, datetime
d = datetime.now()
print(d.strftime('%d-%m-%Y'))
print(d.strftime('%A, %d %B, %y'))
print(d.strftime('%H:%M:%S'))
print(d.strftime('%H horas, %M minutos y %S segundos'))

06-06-2023
Tuesday, 06 June, 23
21:12:11
21 horas, 12 minutos y 11 segundos


4- Conversión de cadenas en fechas

In [58]:
from datetime import date, time, datetime
datetime.strptime('15/4/2020', '%d/%m/%Y')

datetime.datetime(2020, 4, 15, 0, 0)

In [59]:
datetime.strptime('2020-4-15 20:50:30', '%Y-%m-%d %H:%M:%S')

datetime.datetime(2020, 4, 15, 20, 50, 30)

5- Aritmética de fechas

In [60]:
from datetime import date, time, datetime, timedelta
d1 = datetime(2020, 1, 1)
d1 + timedelta(31,3600)

datetime.datetime(2020, 2, 1, 1, 0)

In [61]:
datetime.now() - d1

datetime.timedelta(days=1252, seconds=76673, microseconds=275309)

- INTRODUCCIÓN A LA LIBRERÍA NUMPY

In [62]:
import numpy as np
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)
print()
#Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print()
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
